---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart sample-app
  systemd:
    name: sample-app
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted