all:
  children:
    elk_cluster:
      children:
        elasticsearch:
          hosts:
            elk-master:
              ansible_host: 192.168.198.134
              elasticsearch_node_master: true
        kibana:
          hosts:
            elk-master:
              ansible_host: 192.168.198.134
        logstash:
          hosts:
            elk-logstash:
              ansible_host: 192.168.198.134
        filebeat:
          hosts:
            app-server:
              ansible_host: 192.168.198.131
        sample_app:
          hosts:
            app-server:
              ansible_host: 192.168.198.131

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/elk_key
    elasticsearch_host: "192.168.198.134"
    logstash_host: "192.168.198.134"
