all:
  children:
    elk_cluster:
      children:
        elasticsearch:
          hosts:
            elk-master:
              ansible_host: 192.168.1.10
              elasticsearch_node_master: true
        kibana:
          hosts:
            elk-master:
              ansible_host: 192.168.1.10
        logstash:
          hosts:
            elk-logstash:
              ansible_host: 192.168.1.11
        filebeat:
          hosts:
            app-server:
              ansible_host: 192.168.1.12
        sample_app:
          hosts:
            app-server:
              ansible_host: 192.168.1.12

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/elk_key