---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  retries: 3
  delay: 10
  register: apt_update
  until: apt_update is succeeded

- name: Install common packages
  apt:
    name:
      - curl
      - wget
      - gnupg
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add Elastic repository key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present

- name: Configure firewall
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "22"
    - "9200"
    - "5601"
    - "5044"
  when: inventory_hostname in groups['elk_cluster']